#!/usr/bin/ruby
path = File.dirname($0)
logFileName = "#{path}/run.log"
pidFileName = "#{path}/run.pid"

if(File.exists?(pidFileName))
    pid = File.read(pidFileName)
    pid.chomp!
    puts("Stopping process: #{pid}")
    Process.kill("KILL", pid.to_i)
end
