#!/usr/bin/ruby
require 'json'
require 'tempfile'

if(ARGV.length < 2)
    puts ""
    puts "Usage: #{$0} <storeId> <promoCode>"
    puts ""
    exit
end


storeId   = ARGV[0]
promoCode = ARGV[1]

# Validate Promo
promoFile = Tempfile.new('promo')
promoFile.puts('{')
promoFile.puts('    "storeId": "' + storeId + '",')
promoFile.puts('    "promoCode": "' + promoCode + '"')
promoFile.puts('}')
promoFile.close

promoJson = `rest-client 'http://69.132.51.248:8080/rest/order-pizza/validate-promo' #{promoFile.path}`

puts(promoJson)

promoFile.unlink
