#!/usr/bin/ruby
require 'json'
require 'active_record'

class CreateEntities
    def initialize()
        @systemColumns       = getSystemColumns()
        @systemTypes         = getSystemTypes()
        @activeRecordTypeMap = getActiveRecordTypeMap()
        @entities            = Array.new()

        createEntities()
    end

    def createEntities
        # Create entities json
        i = 0
        previousEntityName = ""
        entities = Array.new()
        members  = Array.new()
        @systemColumns.each do |column|
            member   = Hash.new()


            currentEntityName = column['entity_name']
            memberName        = column['column_name']
            systemTypeId      = column['system_type_id']

            break unless currentEntityName

            memberType        = getMemberType(systemTypeId)
        
            member['name'] = memberName
            member['type'] = memberType
        
            members.push(member)
        
            if(i > 0 && currentEntityName != previousEntityName)
                entity = Hash.new()
                entityName            = String.new(previousEntityName).downcase
                entityName            = ActiveSupport::Inflector.camelize(entityName)
                entity['name']        = entityName
                entity['members']     = members
                entity['connections'] = Array.new()
        
                entities.push(entity)
                members = []
            end 
            previousEntityName = currentEntityName
            i += 1
        end

        puts(JSON.generate(entities))
    end

    def getSystemTypes
        # Get System Types.json
        data = `sqsh -S VitosDevServer -C "SELECT name, system_type_id from sys.types"`
        types = data.split("\n")
        
        return linesToArray(types)
    end

    def getSystemColumns
        # Get Schema
        data = `sqsh -S VitosDevServer -C "SELECT t.name as entity_name, c.name as column_name, c.system_type_id, c.max_length, c.precision FROM sys.tables t inner join sys.columns c on t.object_id = c.object_id where t.type = 'U' Order by t.name, c.name"`
        columns = data.split("\n")
        
        return linesToArray(columns)
    end
    def getActiveRecordTypeMap
        typeMap = Hash.new()
        typeMap['image']     = 'binary'
        typeMap['bit']       = 'Boolean'
        typeMap['datetime']  = 'timestamp'
        typeMap['datetime2'] = 'timestamp'
        typeMap['decimal']   = 'decimal'
        typeMap['float']     = 'float'
        typeMap['int']       = 'integer'
        typeMap['smallint']  = 'integer'
        typeMap['varchar']   = 'string'
        typeMap['nvarchar']  = 'string'
        typeMap['text']      = 'text'

        return typeMap
    end

    def linesToArray(lines)
    
        items = Array.new()
        item  = Hash.new()
        lines.each do |line|
            line.chomp!
            if(line =~ /:/) 
                (key, value) = line.split(/:\s+/)
                item[key] = value
            else
                items.push(item)
                item = {}
            end
        end
    
        return items
    end
    
    def getMemberType(systemTypeId)
        type = ""
        sqlServerType = @systemTypes.select { |systemType| systemType['system_type_id'] == systemTypeId }.first

        type = @activeRecordTypeMap[sqlServerType['name']]
        return type
    end
end

CreateEntities.new()
